const simpleLootTable = new Map

simpleLootTable.set(1,['emerald','绿宝石'])
simpleLootTable.set(2,['emerald','绿宝石'])
simpleLootTable.set(3,['wheat','小麦'])
simpleLootTable.set(4,['wheat','小麦'])
simpleLootTable.set(5,['wooden_hoe','木锄'])
simpleLootTable.set(6,['wooden_hoe','木锄'])
simpleLootTable.set(7,['clay','粘土块'])
simpleLootTable.set(8,['clay','粘土块'])
simpleLootTable.set(9,['brick','红砖'])
simpleLootTable.set(10,['brick','红砖'])
simpleLootTable.set(11,['yellow_dye','黄色染料'])
simpleLootTable.set(12,['yellow_dye','黄色染料'])
simpleLootTable.set(13,['blue_dye','蓝色染料'])
simpleLootTable.set(14,['blue_dye','蓝色染料'])
simpleLootTable.set(15,['light_blue_dye','淡蓝色染料'])
simpleLootTable.set(16,['light_blue_dye','淡蓝色染料'])
simpleLootTable.set(17,['white_dye','白色染料'])
simpleLootTable.set(18,['white_dye','白色染料'])
simpleLootTable.set(19,['orange_dye','橘色染料'])
simpleLootTable.set(20,['orange_dye','橘色染料'])
simpleLootTable.set(21,['green_candle','绿色蜡烛'])
simpleLootTable.set(22,['green_candle','绿色蜡烛'])
simpleLootTable.set(23,['red_candle','红色蜡烛'])
simpleLootTable.set(24,['red_candle','红色蜡烛'])
simpleLootTable.set(25,['purple_candle','紫色蜡烛'])
simpleLootTable.set(26,['purple_candle','紫色蜡烛'])
simpleLootTable.set(27,['brown_candle','棕色蜡烛'])
simpleLootTable.set(28,['brown_candle','棕色蜡烛'])
simpleLootTable.set(29,['magenta_stained_glass_pane_top','品红色玻璃板'])
simpleLootTable.set(30,['pink_stained_glass_pane_top','粉色玻璃板'])
simpleLootTable.set(31,['blue_stained_glass_pane_top','蓝色玻璃板'])
simpleLootTable.set(32,['light_blue_stained_glass_pane_top','淡蓝色玻璃板'])
simpleLootTable.set(33,['red_stained_glass_pane_top','红色玻璃板'])
simpleLootTable.set(34,['yellow_stained_glass_pane_top','黄色玻璃板'])
simpleLootTable.set(35,['purple_stained_glass_pane_top','紫色玻璃板'])
simpleLootTable.set(36,['oak_hanging_sign','悬挂橡木告示牌'])
simpleLootTable.set(37,['spruce_hanging_sign','悬挂云杉木告示牌'])
simpleLootTable.set(38,['gold_nugget','金粒'])
simpleLootTable.set(39,['coal','煤炭'])
simpleLootTable.set(40,['wheat_seeds','小麦种子'])
simpleLootTable.set(41,['beetroot_seeds','甜菜根种子'])
simpleLootTable.set(42,['dead_bush','枯木'])
simpleLootTable.set(43,['flower_pot','花盆'])
simpleLootTable.set(44,['string','线'])
simpleLootTable.set(45,['lead','拴绳'])

const seniorLootTable = new Map

seniorLootTable.set(1,['burn_pottery_sherd','烈焰纹样陶片'])
seniorLootTable.set(2,['danger_pottery_sherd','危机纹样陶片'])
seniorLootTable.set(3,['friend_pottery_sherd','挚友纹样陶片'])
seniorLootTable.set(4,['heart_pottery_sherd','爱心纹样陶片'])
seniorLootTable.set(5,['heartbreak_pottery_sherd','心碎纹样陶片'])
seniorLootTable.set(6,['howl_pottery_sherd','狼嚎纹样陶片'])
seniorLootTable.set(7,['sheaf_pottery_sherd','麦捆纹样陶片'])
seniorLootTable.set(8,['host_armor_trim_smithing_template','雇主盔甲纹饰锻造模板'])
seniorLootTable.set(9,['raiser_armor_trim_smithing_template','牧民盔甲纹饰锻造模板'])
seniorLootTable.set(10,['shaper_armor_trim_smithing_template','塑造盔甲纹饰锻造模板'])
seniorLootTable.set(11,['wayfinder_armor_trim_smithing_template','向导盔甲纹饰锻造模板'])
seniorLootTable.set(12,['music_disc_relic','Relic唱片'])

export{
    simpleLootTable,
    seniorLootTable
}
