const simpleLootTable = new Map

simpleLootTable.set(1,'emerald')
simpleLootTable.set(2,'emerald')
simpleLootTable.set(3,'wheat')
simpleLootTable.set(4,'wheat')
simpleLootTable.set(5,'wooden_hoe')
simpleLootTable.set(6,'wooden_hoe')
simpleLootTable.set(7,'clay')
simpleLootTable.set(8,'clay')
simpleLootTable.set(9,'brick')
simpleLootTable.set(10,'brick')
simpleLootTable.set(11,'yellow_dye')
simpleLootTable.set(12,'yellow_dye')
simpleLootTable.set(13,'blue_dye')
simpleLootTable.set(14,'blue_dye')
simpleLootTable.set(15,'light_blue_dye')
simpleLootTable.set(16,'light_blue_dye')
simpleLootTable.set(17,'white_dye')
simpleLootTable.set(18,'white_dye')
simpleLootTable.set(19,'orange_dye')
simpleLootTable.set(20,'orange_dye')
simpleLootTable.set(21,'green_candle')
simpleLootTable.set(22,'green_candle')
simpleLootTable.set(23,'red_candle')
simpleLootTable.set(24,'red_candle')
simpleLootTable.set(25,'purple_candle')
simpleLootTable.set(26,'purple_candle')
simpleLootTable.set(27,'brown_candle')
simpleLootTable.set(28,'brown_candle')
simpleLootTable.set(29,'magenta_stained_glass_pane_top')
simpleLootTable.set(30,'pink_stained_glass_pane_top')
simpleLootTable.set(31,'blue_stained_glass_pane_top')
simpleLootTable.set(32,'light_blue_stained_glass_pane_top')
simpleLootTable.set(33,'red_stained_glass_pane_top')
simpleLootTable.set(34,'yellow_stained_glass_pane_top')
simpleLootTable.set(35,'purple_stained_glass_pane_top')
simpleLootTable.set(36,'oak_hanging_sign')
simpleLootTable.set(37,'spruce_hanging_sign')
simpleLootTable.set(38,'gold_nugget')
simpleLootTable.set(39,'coal')
simpleLootTable.set(40,'wheat_seeds')
simpleLootTable.set(41,'beetroot_seeds')
simpleLootTable.set(42,'dead_bush')
simpleLootTable.set(43,'flower_pot')
simpleLootTable.set(44,'string')
simpleLootTable.set(45,'lead')

const seniorLootTable = new Map

seniorLootTable.set(1,'burn_pottery_sherd')
seniorLootTable.set(2,'danger_pottery_sherd')
seniorLootTable.set(3,'friend_pottery_sherd')
seniorLootTable.set(4,'heart_pottery_sherd')
seniorLootTable.set(5,'heartbreak_pottery_sherd')
seniorLootTable.set(6,'howl_pottery_sherd')
seniorLootTable.set(7,'sheaf_pottery_sherd')
seniorLootTable.set(8,'host_armor_trim_smithing_template')
seniorLootTable.set(9,'raiser_armor_trim_smithing_template')
seniorLootTable.set(10,'shaper_armor_trim_smithing_template')
seniorLootTable.set(11,'wayfinder_armor_trim_smithing_template')
seniorLootTable.set(12,'music_disc_relic')

export{
    simpleLootTable,
    seniorLootTable
}
